--https://school.programmers.co.kr/learn/courses/30/lessons/131120 
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') as DATE_OF_BIRTH
FROM MEMBER_PROFILE as T
WHERE(GENDER = 'W' AND SUBSTR(DATE_OF_BIRTH, 6, 2) = '03' AND T.TLNO IS NOT NULL)